spring:
  application:
        name: video_player_be

server:
  port: ${PORT:8082}
  forward-headers-strategy: framework

app:
  streams-folder: ${STREAMS_FOLDER:./streams}
  ffmpeg-path: ${FFMPEG_PATH:ffmpeg}

logging:
  level:
    root: INFO
